- name: yum update
  yum:
    name: '*'
    state: latest
- name: install python deps
  yum:
    name:
      - gcc
      - gcc-c++
      - make
      - wget
      - zlib-devel
      - bzip2
      - bzip2-devel
      - openssl-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - curl
      - git
      - patch
      - file
      - automake
- name: get pyenv installer
  get_url:
    url: https://pyenv.run
    dest: /tmp/pyenv.sh
    mode: u=rwx,g=rx,o=rx
- name: install pyenv
  shell: |
    bash /tmp/pyenv.sh
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc 
    . ~/.bashrc